-- 1.List the top 3 customers who have placed the highest number of orders.

select c.customer_id,
    c.customer_name,
    count(od.order_id) as total_orders
from customer c
join order_detail od on c.customer_id = od.customer_id
group by c.customer_id, c.customer_name
order by total_orders desc
limit 3;


-- 2.Find the restaurant that has received the highest average rating.
select restaurant_id,restaurant_name,rlocation ,rrating
from restaurant
where rrating > ( select 
				AVG(rrating) from  restaurant) 
group by restaurant_id,restaurant_name
order by ( select 
				AVG(rrating) from  restaurant) Desc
limit 3;

-- 3.List all orders from order_detail that were delivered in under 30 minutes.
select *from order_detail
where timestampdiff(minute,order_time,delivered_time) < 30;

-- 4.Calculate the total revenue generated by each food item. Display food_id, food_name and Total revenue ordered by total revenue in descending order.
select  
    f.food_id,
    f.food_name,
    sum(f.price_per_unit * od.quantity) as total_revenue
from foods f
join  order_food od on f.food_id = od.food_id
group by f.food_id, f.food_name
order by total_revenue desc;

-- 5.Find the second highest revenue-generating restaurant.
Select r.restaurant_id,r.restaurant_name, SUM(o.quantity*f.price_per_unit) as Total_Revenue 
from restaurant as  r 
join  order_food as o on r.restaurant_id = o.restaurant_id 
join  foods as f on f.food_id = o.food_id
group by r.restaurant_id,r.restaurant_name 
order by Total_Revenue DESC
limit 1 offset 1;
 
-- 6.Find the 5 most popular food items based on the quantity sold.
select 
    f.food_id,
    f.food_name,
    sum(od.quantity) as total_quantity_sold
from foods f
join order_food od on f.food_id = od.food_id
group by f.food_id, f.food_name
order by total_quantity_sold desc
limit 5;


-- 7.List the top 3 Zomato employees with the highest average delivery ratings.

select * from zomato_employee;
select * from zomato_employee
order by employee_avg_rating DESC
limit 3;

-- 8.Determine the month with the highest number of total orders placed.

select *from order_detail;
select date_format(order_time,'%M') AS order_month,
		count(order_id) AS total_order
from order_detail
group by order_month
order by  total_order desc
limit 1;

-- 9.Calculate the average order amount for each customer. Order by average order amount in descending order.
select 
	c.customer_id ,c.customer_name, 
    avg(f.price_per_unit*odf.quantity)AS Avg_Order_amt
from customer As c
join order_food AS odf on c.customer_id = odf.customer_id
join foods as f on odf.food_id= f.food_id
group by c.customer_id ,c.customer_name
order by Avg_Order_amt DESC;

-- 10.Identify the most frequent customer for each restaurant.
WITH CustomerOrderCount AS (
     select
        restaurant_id,
        customer_id,
        count(*) as order_count
    from order_detail
    group by restaurant_id, customer_id
),
RankedCustomers as(
    select *,
		  rank() over (
               partition by restaurant_id
               order by  order_count desc
           )  as rank_in_restaurant
    from CustomerOrderCount
)
select r.restaurant_id, r.restaurant_name, rc.customer_id, rc.order_count
from RankedCustomers rc
join  restaurant r on rc.restaurant_id = r.restaurant_id
where rank_in_restaurant = 1;

-- 11.Calculate the total number of orders placed on weekends.

select *from order_detail;
select 
	count(*) AS WEEKEND_OFF
from order_detail
where dayofweek(order_time) in (1,7);

-- 12.Calculate the average delivery time (in minutes) for orders placed on weekdays versus weekends.

SELECT 
    CASE 
        WHEN DAYOFWEEK(order_time) IN (1, 7) THEN 'Weekend'
        ELSE 'Weekday'
    END AS day_type,
    AVG(TIMESTAMPDIFF(MINUTE, order_time, delivered_time)) AS avg_delivery_time_minutes
FROM 
    order_detail
GROUP BY 
    day_type;
    
 -- 13.List the top 5 most expensive food items. Display food_id, food_name, and price_per_unit for all food items with the highest 5 prices.


WITH RankedFoods AS (
    SELECT 
        food_id,
        food_name,
        price_per_unit,
        RANK() OVER (ORDER BY price_per_unit DESC) AS price_rank
    FROM foods
)
SELECT 
    food_id,
    food_name,
    price_per_unit
FROM RankedFoods
WHERE price_rank <= 5;

-- 14.Find the restaurant with the most diverse menu (i.e., the highest number of food items).
select r.restaurant_id, r.restaurant_name ,
		count( distinct ofd.food_id) AS total_foods
from restaurant as r
join order_food as ofd on  r.restaurant_id = ofd.restaurant_id
group by r.restaurant_id, r.restaurant_name 
order by total_foods desc
limit 3;

-- 15.Calculate total payment amount for each payment type.

select *from payment_table;
select p.payment_type , sum(odf.quantity*f.price_per_unit)AS TOTAL_AMOUNT
from payment_table as p
join order_food as odf on p.order_id = odf.order_id
join foods as f on f.food_id=odf.food_id
group by p.payment_type 
order  by TOTAL_AMOUNT desc;  

-- 16.Food item with least revenue but ordered at least 10 times.
SELECT 
    f.food_id,
    f.food_name,
    SUM(od.quantity * f.price_per_unit) AS total_revenue,
    SUM(od.quantity) AS total_quantity
FROM foods f
JOIN order_food od ON f.food_id = od.food_id
GROUP BY f.food_id, f.food_name
HAVING SUM(od.quantity) >= 10
ORDER BY total_revenue ASC
LIMIT 1;
